#!/System/Index/Binaries/ash

#Prevent kernel messages to console
dmesg -n 1

#Mount RAM drives
mkdir -p /dev/pts
mkdir -p /dev/shm
mount -t devpts -o gid=4,mode=620 none /dev/pts
mount -t tmpfs none /dev/shm

#Set hostname
hostname -F /System/Settings/hostname

#Empty temp and run dirs
rm -rf /System/Temporary/*
rm -rf /System/State/run/*

#Start system logger
syslogd -O /System/Logs/syslog

#Start kernel logger
klogd

#Mount proc and sys filesystems
mount -t proc none /System/Kernel/Status
mount -t sysfs none /System/Kernel/Hardware

#Print system log to tty10 (ALT+F10)
tail -f /System/Logs/syslog > /System/Kernel/Devices/tty10 &

#Load modules for auto-detected hardware
grep -h MODALIAS /System/Kernel/Hardware/bus/*/devices/*/uevent 2> /dev/null | cut -d= -f2 | sort -u | xargs modprobe -abq 2> /dev/null

#Start cron daemon
crond -c /System/Settings/crond

#Hide all legacy directories
gobohide -h /bin /boot /etc /lib /libexec /media /mnt /lost\+found /proc /sbin /share /sys /tmp /var /dev /usr /include

#Start all network interfaces
ifup -a
